### PR TITLE
This is a small tweak that preserves the last message send when decod…

### PR DESCRIPTION
**Pull request by natcl**
…ing.

### CODE REVIEW

**Comment by njh** [comment]
Hi!

Any background on why this is useful?

nick.

**Comment by natcl** [comment]
I’m using the serial request node with slip on either side, my request to the serial port originates from an http request so I need to preserve the http metdata, without this anything else than payload is lost.


--
lecaude.com 
studioimaginaire.com

**Comment by natcl** [comment]
Polite bump

**Comment by natcl** [comment]
Thanks!!


--
lecaude.com 
studioimaginaire.com

**Pull request merged**
